# Generated by Django 2.2.1 on 2019-05-11 20:19

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maretial',
            new_name='Material',
        ),
    ]
